<?php

$title = 'All Articles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('article', array('action' => 'add')); ?>">Add new article</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($articles as $article) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($article->title); ?></td>
            <td><?php echo $this->escapeHtml($article->content); ?></td>
            <td>
                <a href="<?php echo $this->url(
                                'article',
                                array('action' => 'edit', 'id' => $article->id)
                            ); ?>">Edit</a>
                <a href="<?php echo $this->url(
                                'article',
                                array('action' => 'delete', 'id' => $article->id)
                            ); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>